bcgov/EDUC-GRAD-GRADUATION-REPORT-API

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/GradStudentReports.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/GradStudentTranscripts.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/GraduationStudentRecordSearchResult.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/entity/GradStudentReportsEntity.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/entity/GradStudentTranscriptsEntity.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/transformer/GradStudentTranscriptsTransformer.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/repository/GradStudentReportsRepository.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/repository/GradStudentTranscriptsRepository.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
GRAD2-1591: task is completed.
> GRAD2-1591: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
Transcript Distribution date should always get updated
> GRAD2-1619

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
GRAD2-1857 RC - User reprint of certificate should not update Distribution Date
> Don't update Dist Date if RC

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
GRAD2-1857 RC - User reprint of certificate should not update Distribution Date
> Don't update Dist Date if USERDISTRC

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
- api/src/test/resources/application.yaml
> GRAD2-1923 : task is complete

- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- Dockerfile
- api/src/main/resources/application.yaml
- tools/openshift/api.dc.yaml
Grad Graduation Report API resource optimization is done
> GRAD2-1947 Resource optmization

- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/GradStudentCertificates.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
> GRAD2-1966 : task is complete

- api/src/main/java/ca/bc/gov/educ/api/grad/report/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
Refactoring is done with Grad Graduation Report API
> Grad2-1929 Refactor/Lint

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
> GRAD2-2166: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/grad/report/repository/GradStudentTranscriptsRepository.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
GRAD2-2255: task is completed.
> GRAD2-2255: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/ReportGradStudentData.java
GRAD2-2280: year-end dist is fixed.
> GRAD2-2280: year-end dist is fixed.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/StudentSearchRequest.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
> Grad release 1.10.0

- api/src/main/java/ca/bc/gov/educ/api/grad/report/config/RestWebClient.java
Unexpected Internal Server Error for TVRs for Projected Non-Grads
> GRAD2-2408

- api/pom.xml
> Sync from main

- README.md
- tools/openshift/api.dc.yaml
move grad client credentials from config-map to secret
> move grad client credentials from config-map to secret

- api/src/main/java/ca/bc/gov/educ/api/grad/report/controller/CommonController.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/controller/CommonControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
GRAD2-2465 - Delete a student and related data
> GRAD2-2465 - Delete a student and related data

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
HD-22859 (GRAD) YE Distribution run should direct Certificates to School at Graduation, not School of Record
> GRAD2-2377

- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
(GRAD) Fix User Request Distribution Run options - Part 2 - CUR and Null Distribution Dates
> GRAD2-2580

- api/src/main/java/ca/bc/gov/educ/api/grad/report/controller/CommonController.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/repository/GradStudentReportsRepository.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/util/EducGradReportApiConstants.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/controller/CommonControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
TVR Delete Process - Backend Changes Endpoints
> GRAD2-2817

- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/StudentSearchRequest.java
User Distribution Run downloaded report files are empty
> GRAD2-2958

- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/District.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/School.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/CommonService.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/CommonServiceTest.java
- api/src/test/resources/application.yaml
> GRAD2-2761: task is complete.

- .github/dependabot.yml
- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
> Grad2-3132 ZAPscan version upgraded

- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/create_tag.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- .github/workflows/on.pr.yml
- tools/openshift/api.dc.yaml
> Grad2-3111 converted grad graduation report api deployment

- api/src/main/java/ca/bc/gov/educ/api/grad/report/model/dto/School.java
GRAD2-2761: districtId is newly added into School Clob.
> GRAD2-2761: districtId is newly added into School Clob.

- api/src/main/java/ca/bc/gov/educ/api/grad/report/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/service/v2/RESTService.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/util/EducGradReportApiConstants.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/util/LogHelper.java
- api/src/main/java/ca/bc/gov/educ/api/grad/report/util/ThreadLocalStateUtil.java
- api/src/test/java/ca/bc/gov/educ/api/grad/report/service/v2/RESTServicePOSTTest.java
> Grad2-3284 Set Request Headers
